"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { Archive, ArrowLeft, ExternalLink, Plus, RotateCw, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Badge, MetricCard, TimelineItem } from "@/components/ui/data-display";
import { Alert, EmptyState, Skeleton } from "@/components/ui/feedback";
import { Checkbox, FormField, Input, Select } from "@/components/ui/form-controls";
import { Breadcrumb, PageHeader, SectionHeader } from "@/components/ui/navigation";
import { Tabs } from "@/components/ui/overlays";
import { toAppError } from "@/lib/errors/app-error";
import { changeClientStage, createContact, deleteContact, setClientArchived, updateContact } from "../api/clients";
import { clientKeys, useClient } from "../hooks/use-clients";
import { clientStages, type ClientDetail as ClientDetailType, type ClientStatus } from "../types/client";

export function ClientDetail({ clientId }: { clientId: string }) {
  const router = useRouter();
  const queryClient = useQueryClient();
  const query = useClient(clientId);
  const refresh = () => queryClient.invalidateQueries({ queryKey: clientKeys.all });
  const stage = useMutation({ mutationFn: (value: (typeof clientStages)[number]) => changeClientStage(clientId, value), onSuccess: refresh });
  const archive = useMutation({ mutationFn: (value: boolean) => setClientArchived(clientId, value), onSuccess: refresh });
  if (query.isLoading) return <DetailSkeleton />;
  if (query.isError) { const error = toAppError(query.error); return <><PageHeader title="Client" breadcrumb={<Breadcrumb items={[{ label: "Clients", href: "/clients" }, { label: "Client" }]} />} /><Alert variant="danger" title={error.status === 404 ? "Client not found" : "Client could not be loaded"} action={<Button variant="secondary" size="sm" onClick={() => void query.refetch()}><RotateCw aria-hidden className="size-4" />Retry</Button>}>{error.message}</Alert></>; }
  if (!query.data) return null;
  const client = query.data;
  const actionError = stage.error ?? archive.error;
  return <><PageHeader title={client.name} description={client.description ?? "No description has been added."} breadcrumb={<Breadcrumb items={[{ label: "Clients", href: "/clients" }, { label: client.name }]} />} actions={<><Button variant="secondary" onClick={() => router.back()}><ArrowLeft aria-hidden className="size-4" />Back</Button><Button variant="secondary" onClick={() => router.push(`/clients/${client.id}/edit`)}>Edit client</Button><Button variant={client.status === "ARCHIVED" ? "secondary" : "danger"} loading={archive.isPending} onClick={() => archive.mutate(client.status !== "ARCHIVED")}><Archive aria-hidden className="size-4" />{client.status === "ARCHIVED" ? "Restore" : "Archive"}</Button></>} />{actionError ? <Alert variant="danger" title="Client could not be updated">{toAppError(actionError).message}</Alert> : null}<div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Status" value={<StatusBadge status={client.status} />} /><MetricCard label="Pipeline" value={label(client.stage)} /><MetricCard label="Contacts" value={client.contacts.length} /><MetricCard label="Last updated" value={format(new Date(client.updatedAt), "d MMM yyyy")} /></div><section className="rounded-[var(--radius-lg)] border bg-surface p-4 md:p-6"><Tabs defaultValue="overview" items={[{ value: "overview", label: "Overview", content: <Overview client={client} onStageChange={(value) => stage.mutate(value)} stagePending={stage.isPending} /> }, { value: "contacts", label: `Contacts (${client.contacts.length})`, content: <Contacts client={client} /> }, { value: "projects", label: `Projects (${client.projects.length})`, content: <Projects client={client} /> }, { value: "meetings", label: `Meetings (${client.meetings.length})`, content: <Meetings client={client} /> }, { value: "activity", label: `Activity (${client.activity.length})`, content: client.activity.length ? <ol>{client.activity.map((item) => <TimelineItem key={item.id} title={label(item.action.replaceAll(".", "_"))} description={item.actor.name} timestamp={format(new Date(item.createdAt), "d MMM yyyy, HH:mm")} />)}</ol> : <CompactEmpty title="No activity yet" /> }]} /></section></>;
}

function Overview({ client, onStageChange, stagePending }: { client: ClientDetailType; onStageChange: (value: (typeof clientStages)[number]) => void; stagePending: boolean }) {
  return <div className="grid gap-8 lg:grid-cols-2"><div><SectionHeader title="Client details" /><dl className="grid gap-4 text-sm sm:grid-cols-2"><Field label="Email" value={client.email ? <a className="underline" href={`mailto:${client.email}`}>{client.email}</a> : "Not provided"} /><Field label="Phone" value={client.phone ?? "Not provided"} /><Field label="Website" value={client.website ? <a className="inline-flex items-center gap-1 underline" href={client.website} target="_blank" rel="noreferrer">Open website<ExternalLink aria-hidden className="size-3" /></a> : "Not provided"} /><Field label="Created" value={format(new Date(client.createdAt), "d MMM yyyy")} /></dl></div><div><SectionHeader title="Pipeline stage" description="Changing this value updates the backend immediately." /><Select aria-label="Client pipeline stage" value={client.stage} disabled={stagePending || client.status === "ARCHIVED"} onValueChange={(value) => onStageChange(value as (typeof clientStages)[number])}>{clientStages.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></div></div>;
}

function Contacts({ client }: { client: ClientDetailType }) {
  const queryClient = useQueryClient();
  const [adding, setAdding] = useState(false);
  const refresh = () => queryClient.invalidateQueries({ queryKey: clientKeys.detail(client.id) });
  const create = useMutation({ mutationFn: (input: Parameters<typeof createContact>[1]) => createContact(client.id, input), onSuccess: () => { setAdding(false); void refresh(); } });
  const remove = useMutation({ mutationFn: (contactId: string) => deleteContact(client.id, contactId), onSuccess: refresh });
  const update = useMutation({ mutationFn: (contactId: string) => updateContact(client.id, contactId, { isPrimary: true }), onSuccess: refresh });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ firstName: String(data.get("firstName") ?? ""), lastName: String(data.get("lastName") ?? ""), ...optionalContactField(data, "email"), ...optionalContactField(data, "phone"), ...optionalContactField(data, "jobTitle"), isPrimary: data.get("isPrimary") === "on" }); };
  return <div className="grid gap-4"><div className="flex justify-end"><Button size="sm" disabled={client.status === "ARCHIVED"} onClick={() => setAdding((value) => !value)}><Plus aria-hidden className="size-4" />Add contact</Button></div>{adding ? <form onSubmit={submit} className="grid gap-3 rounded-[var(--radius-md)] border p-4 sm:grid-cols-2"><FormField label="First name" required><Input name="firstName" required minLength={2} /></FormField><FormField label="Last name" required><Input name="lastName" required minLength={2} /></FormField><FormField label="Job title"><Input name="jobTitle" /></FormField><FormField label="Email"><Input name="email" type="email" /></FormField><FormField label="Phone"><Input name="phone" /></FormField><Checkbox name="isPrimary" label="Primary contact" /><div className="sm:col-span-2"><Button type="submit" loading={create.isPending}>Save contact</Button></div>{create.error ? <div className="sm:col-span-2"><Alert variant="danger" title="Contact could not be saved">{toAppError(create.error).message}</Alert></div> : null}</form> : null}{client.contacts.length ? <div className="grid gap-3 md:grid-cols-2">{client.contacts.map((contact) => <article key={contact.id} className="rounded-[var(--radius-md)] border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{contact.firstName} {contact.lastName}</h3><p className="text-sm text-text-secondary">{contact.jobTitle ?? "No job title"}</p></div>{contact.isPrimary ? <Badge tone="info">Primary</Badge> : null}</div><p className="mt-4 text-sm">{contact.email ? <a className="underline" href={`mailto:${contact.email}`}>{contact.email}</a> : "No email"}</p><p className="mt-1 text-sm text-text-secondary">{contact.phone ?? "No phone"}</p><div className="mt-3 flex flex-wrap gap-2">{!contact.isPrimary ? <Button variant="secondary" size="sm" loading={update.isPending && update.variables === contact.id} onClick={() => update.mutate(contact.id)}>Make primary</Button> : null}<Button variant="ghost" size="sm" loading={remove.isPending && remove.variables === contact.id} onClick={() => remove.mutate(contact.id)}><Trash2 aria-hidden className="size-4" />Remove</Button></div></article>)}</div> : <CompactEmpty title="No contacts" />}{update.error ? <Alert variant="danger" title="Contact could not be updated">{toAppError(update.error).message}</Alert> : null}</div>;
}

function Projects({ client }: { client: ClientDetailType }) { return client.projects.length ? <div className="divide-y rounded-[var(--radius-md)] border">{client.projects.map((project) => <a href={`/projects/${project.id}`} key={project.id} className="flex items-center justify-between gap-4 p-4 hover:bg-surface-hover"><div><p className="text-sm font-medium">{project.name}</p><p className="mt-1 text-xs text-text-muted">{project.dueDate ? `Due ${format(new Date(project.dueDate), "d MMM yyyy")}` : "No due date"}</p></div><Badge>{label(project.status)}</Badge></a>)}</div> : <CompactEmpty title="No related projects" />; }
function Meetings({ client }: { client: ClientDetailType }) { return client.meetings.length ? <div className="divide-y rounded-[var(--radius-md)] border">{client.meetings.map((meeting) => <div key={meeting.id} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-medium">{meeting.title}</p><p className="mt-1 text-xs text-text-muted">{format(new Date(meeting.startsAt), "d MMM yyyy, HH:mm")}</p></div><Badge tone={meeting.cancelledAt ? "danger" : "info"}>{meeting.cancelledAt ? "Cancelled" : "Scheduled"}</Badge></div>)}</div> : <CompactEmpty title="No related meetings" />; }
function CompactEmpty({ title }: { title: string }) { return <EmptyState title={title} description="The backend has not returned any records for this section." />; }
function Field({ label: term, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs text-text-muted">{term}</dt><dd className="mt-1 text-text-primary">{value}</dd></div>; }
function StatusBadge({ status }: { status: ClientStatus }) { return <Badge tone={status === "ACTIVE" ? "success" : "neutral"}>{label(status)}</Badge>; }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
function optionalContactField<Key extends string>(data: FormData, key: Key): Partial<Record<Key, string>> { const value = String(data.get(key) ?? "").trim(); return value ? { [key]: value } as Partial<Record<Key, string>> : {}; }
function DetailSkeleton() { return <div role="status" aria-label="Loading client details" className="grid gap-6"><span className="sr-only">Loading client details</span><Skeleton className="h-24 w-full" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-28" />)}</div><Skeleton className="h-96" /></div>; }
