"use client";

import { format } from "date-fns";
import { ArrowLeft, ExternalLink, RotateCw } from "lucide-react";

import { Badge, MetricCard, TimelineItem } from "@/components/ui/data-display";
import { Button } from "@/components/ui/button";
import { Alert, EmptyState, Skeleton } from "@/components/ui/feedback";
import { Breadcrumb, PageHeader, SectionHeader } from "@/components/ui/navigation";
import { Tabs } from "@/components/ui/overlays";
import { toAppError } from "@/lib/errors/app-error";
import { useClient } from "../hooks/use-clients";
import type { ClientDetail as ClientDetailType, ClientStatus, RelatedRecord } from "../types/client";

export function ClientDetail({ clientId }: { clientId: string }) {
  const query = useClient(clientId);
  if (query.isLoading) return <DetailSkeleton />;
  if (query.isError) { const error = toAppError(query.error); return <><PageHeader title="Client" breadcrumb={<Breadcrumb items={[{ label: "Clients", href: "/clients" }, { label: "Client" }]} />} /><Alert variant="danger" title={error.status === 404 ? "Client not found" : "Client could not be loaded"} action={<Button variant="secondary" size="sm" onClick={() => void query.refetch()}><RotateCw aria-hidden className="size-4" />Retry</Button>}>{error.message}</Alert></>; }
  if (!query.data) return null;
  const client = query.data;
  return <><PageHeader title={client.name} description={client.summary} breadcrumb={<Breadcrumb items={[{ label: "Clients", href: "/clients" }, { label: client.name }]} />} actions={<><Button variant="secondary" onClick={() => history.back()}><ArrowLeft aria-hidden className="size-4" />Back</Button><Button variant="secondary" onClick={() => location.assign(`/clients/${client.id}/edit`)}>Edit client</Button></>} /><div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Status" value={<StatusBadge status={client.status} />} /><MetricCard label="Pipeline" value={label(client.pipelineStage)} /><MetricCard label="Relationship owner" value={client.owner.name} /><MetricCard label="Last updated" value={format(new Date(client.updatedAt), "d MMM yyyy")} /></div><section className="rounded-[var(--radius-lg)] border bg-surface p-4 md:p-6"><Tabs defaultValue="overview" items={[{ value: "overview", label: "Overview", content: <Overview client={client} /> }, { value: "contacts", label: `Contacts (${client.contacts.length})`, content: <Contacts client={client} /> }, { value: "notes", label: `Notes (${client.notes.length})`, content: client.notes.length ? <div className="grid gap-3">{client.notes.map((note) => <article key={note.id} className="rounded-[var(--radius-md)] border p-4"><p className="text-sm">{note.body}</p><p className="mt-3 text-xs text-text-muted">{note.author.name} · {format(new Date(note.createdAt), "d MMM yyyy, HH:mm")}</p></article>)}</div> : <CompactEmpty title="No notes" /> }, { value: "projects", label: `Projects (${client.projects.length})`, content: <RelatedList records={client.projects} empty="No related projects" /> }, { value: "meetings", label: `Meetings (${client.meetings.length})`, content: <RelatedList records={client.meetings} empty="No related meetings" /> }, { value: "documents", label: `Documents (${client.documents.length})`, content: <RelatedList records={client.documents} empty="No related documents" /> }, { value: "activity", label: "Activity", content: <ol>{client.activity.map((item) => <TimelineItem key={item.id} title={item.action} description={`${item.description} · ${item.actor}`} timestamp={format(new Date(item.createdAt), "d MMM yyyy, HH:mm")} />)}</ol> }]} /></section></>;
}

function Overview({ client }: { client: ClientDetailType }) { return <div className="grid gap-8 lg:grid-cols-2"><div><SectionHeader title="Client details" /><dl className="grid gap-4 text-sm sm:grid-cols-2"><Field label="Industry" value={client.industry} /><Field label="Email" value={<a className="underline" href={`mailto:${client.primaryEmail}`}>{client.primaryEmail}</a>} /><Field label="Phone" value={client.phone} /><Field label="Website" value={<a className="inline-flex items-center gap-1 underline" href={client.website} target="_blank" rel="noreferrer">Open website<ExternalLink aria-hidden className="size-3" /></a>} /><Field label="Address" value={client.address} /><Field label="Created" value={format(new Date(client.createdAt), "d MMM yyyy")} /></dl></div><div><SectionHeader title="Next related items" description="Display-only references from the provisional aggregate." /><RelatedList records={[...client.projects, ...client.meetings].slice(0, 3)} empty="No related work yet" /></div></div>; }
function Contacts({ client }: { client: ClientDetailType }) { return client.contacts.length ? <div className="grid gap-3 md:grid-cols-2">{client.contacts.map((contact) => <article key={contact.id} className="rounded-[var(--radius-md)] border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{contact.name}</h3><p className="text-sm text-text-secondary">{contact.jobTitle}</p></div>{contact.isPrimary ? <Badge tone="info">Primary</Badge> : null}</div><p className="mt-4 text-sm"><a className="underline" href={`mailto:${contact.email}`}>{contact.email}</a></p><p className="mt-1 text-sm text-text-secondary">{contact.phone}</p></article>)}</div> : <CompactEmpty title="No contacts" />; }
function RelatedList({ records, empty }: { records: RelatedRecord[]; empty: string }) { return records.length ? <div className="divide-y rounded-[var(--radius-md)] border">{records.map((record) => <div key={record.id} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-medium">{record.title}</p><p className="mt-1 text-xs text-text-muted">Updated {format(new Date(record.updatedAt), "d MMM yyyy")}</p></div><Badge>{label(record.status)}</Badge></div>)}</div> : <CompactEmpty title={empty} />; }
function CompactEmpty({ title }: { title: string }) { return <EmptyState title={title} description="Related records will appear here when supported data is available." />; }
function Field({ label: term, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs text-text-muted">{term}</dt><dd className="mt-1 text-text-primary">{value}</dd></div>; }
function StatusBadge({ status }: { status: ClientStatus }) { return <Badge tone={status === "ACTIVE" ? "success" : status === "PROSPECT" ? "info" : status === "PAUSED" ? "warning" : "neutral"}>{label(status)}</Badge>; }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
function DetailSkeleton() { return <div role="status" aria-label="Loading client details" className="grid gap-6"><span className="sr-only">Loading client details</span><Skeleton className="h-24 w-full" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-28" />)}</div><Skeleton className="h-96" /></div>; }
