"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { Archive, CalendarDays, Check, ExternalLink, Plus, RotateCw, Trash2, UsersRound } from "lucide-react";
import Link from "next/link";
import { useState, type FormEvent, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Badge, MetricCard, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/data-display";
import { Alert, EmptyState, Skeleton } from "@/components/ui/feedback";
import { FormField, Input, Select, Textarea } from "@/components/ui/form-controls";
import { PageHeader, SectionHeader } from "@/components/ui/navigation";
import { Tabs } from "@/components/ui/overlays";
import { toAppError } from "@/lib/errors/app-error";
import {
  addProjectMember, cancelMeeting, changeProjectStatus, completeMilestone,
  createMeeting, createMilestone, createProject, deleteMilestone, inviteUser,
  invitationStatuses, listClientOptions, listInvitations, listMeetings, listMilestones,
  listProjectMembers, listProjects, listUsers, getProject, projectPriorities, projectRoles,
  projectStatuses, removeProjectMember, resendInvitation, revokeInvitation,
  setProjectArchived, setUserActive, workspaceKeys,
  updateMeeting, updateMilestone, updateProject, updateProjectMemberRole, updateUser,
  type ClientOption, type EmailDeliveryStatus, type InvitationStatus, type MeetingView, type ProjectPriority, type ProjectStatus,
  type MeetingInput, type ProjectInput, type ProjectRole,
} from "../api/workspace";

type MutationLike<TVariables> = {
  mutate: (variables: TVariables) => void;
  isPending: boolean;
  error: unknown;
};

export function DashboardScreen() {
  const query = useQuery({
    queryKey: workspaceKeys.dashboard(),
    queryFn: async ({ signal }) => {
      const [clients, projects, meetings] = await Promise.all([
        listClientOptions(signal),
        listProjects({ archived: false }, signal),
        listMeetings("upcoming", {}, signal),
      ]);
      return { clients, projects, meetings };
    },
  });
  if (query.isLoading) return <ScreenSkeleton title="Dashboard" />;
  if (query.isError || !query.data) return <ScreenError title="Dashboard" error={query.error} retry={() => query.refetch()} />;
  const { clients, projects, meetings } = query.data;
  const activeProjects = projects.filter((project) => project.status === "IN_PROGRESS").length;
  const completedProjects = projects.filter((project) => project.status === "COMPLETED").length;
  return <><PageHeader title="Dashboard" description="A live summary assembled from the currently available API modules." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Clients" value={clients.filter((client) => client.status === "ACTIVE").length} hint="Active client records" /><MetricCard label="Projects" value={projects.length} hint={`${activeProjects} in progress`} /><MetricCard label="Completed" value={completedProjects} hint="Completed projects" /><MetricCard label="Upcoming meetings" value={meetings.length} hint="Scheduled and not cancelled" /></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Recent projects">{projects.length ? <div className="divide-y">{projects.slice(0, 6).map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="flex items-center justify-between gap-4 py-3 hover:text-brand"><div><p className="text-sm font-medium">{project.name}</p><p className="text-xs text-text-muted">{clientName(clients, project.clientId)}</p></div><Badge tone={projectTone(project.status)}>{label(project.status)}</Badge></Link>)}</div> : <CompactEmpty title="No projects yet" />}</Panel><Panel title="Upcoming meetings">{meetings.length ? <div className="divide-y">{meetings.slice(0, 6).map((meeting) => <div key={meeting.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium">{meeting.title}</p><p className="text-xs text-text-muted">{format(new Date(meeting.startsAt), "d MMM yyyy, HH:mm")}</p></div><CalendarDays aria-hidden className="size-4 text-brand" /></div>)}</div> : <CompactEmpty title="No upcoming meetings" />}</Panel></div></>;
}

export function ProjectsScreen() {
  const queryClient = useQueryClient();
  const [adding, setAdding] = useState(false);
  const [status, setStatus] = useState<"" | ProjectStatus>("");
  const [priority, setPriority] = useState<"" | ProjectPriority>("");
  const filters = { ...(status ? { status } : {}), ...(priority ? { priority } : {}), archived: false };
  const query = useQuery({ queryKey: workspaceKeys.projects(filters), queryFn: ({ signal }) => Promise.all([listProjects(filters, signal), listClientOptions(signal)]).then(([projects, clients]) => ({ projects, clients })) });
  const create = useMutation({ mutationFn: createProject, onSuccess: async () => { setAdding(false); await queryClient.invalidateQueries({ queryKey: workspaceKeys.all }); } });
  return <><PageHeader title="Projects" description="Live projects, priorities, deadlines, and delivery status." actions={<Button size="sm" onClick={() => setAdding((value) => !value)}><Plus aria-hidden className="size-4" />Add project</Button>} />{adding ? <ProjectCreateForm clients={query.data?.clients ?? []} mutation={create} /> : null}<div className="surface-panel mb-3 grid gap-2 p-2.5 sm:grid-cols-2"><Select aria-label="Filter projects by status" value={status} onValueChange={(value) => setStatus(value as "" | ProjectStatus)}><option value="">All statuses</option>{projectStatuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select><Select aria-label="Filter projects by priority" value={priority} onValueChange={(value) => setPriority(value as "" | ProjectPriority)}><option value="">All priorities</option>{projectPriorities.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></div>{query.isLoading ? <Skeleton className="h-72" /> : query.isError || !query.data ? <ScreenError title="Projects could not be loaded" error={query.error} retry={() => query.refetch()} compact /> : query.data.projects.length ? <Panel title=""><Table><TableHead><tr><TableHeader>Project</TableHeader><TableHeader>Client</TableHeader><TableHeader>Status</TableHeader><TableHeader>Priority</TableHeader><TableHeader>Due date</TableHeader></tr></TableHead><TableBody>{query.data.projects.map((project) => <TableRow key={project.id}><TableCell><Link href={`/projects/${project.id}`} className="font-medium hover:underline">{project.name}</Link></TableCell><TableCell>{clientName(query.data.clients, project.clientId)}</TableCell><TableCell><Badge tone={projectTone(project.status)}>{label(project.status)}</Badge></TableCell><TableCell>{label(project.priority)}</TableCell><TableCell>{project.dueDate ? format(new Date(project.dueDate), "d MMM yyyy") : "Not set"}</TableCell></TableRow>)}</TableBody></Table></Panel> : <CompactEmpty title="No projects found" />}</>;
}

export function ProjectWorkspaceScreen({ projectId }: { projectId: string }) {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: workspaceKeys.project(projectId), queryFn: async ({ signal }) => { const [project, milestones, members, meetings, clients, users] = await Promise.all([getProject(projectId, signal), listMilestones(projectId, signal), listProjectMembers(projectId, signal), listMeetings("all", { projectId }, signal), listClientOptions(signal), listUsers(1, 100, signal).then((result) => result.data)]); return { project, milestones, members, meetings, clients, users }; } });
  const refresh = () => queryClient.invalidateQueries({ queryKey: workspaceKeys.project(projectId) });
  const status = useMutation({ mutationFn: (value: ProjectStatus) => changeProjectStatus(projectId, value), onSuccess: refresh });
  const priorityUpdate = useMutation({ mutationFn: (value: ProjectPriority) => updateProject(projectId, { priority: value }), onSuccess: refresh });
  const archive = useMutation({ mutationFn: (value: boolean) => setProjectArchived(projectId, value), onSuccess: refresh });
  const milestoneCreate = useMutation({ mutationFn: (input: { title: string; description?: string; dueDate?: string }) => createMilestone(projectId, input), onSuccess: refresh });
  const milestoneComplete = useMutation({ mutationFn: (id: string) => completeMilestone(projectId, id), onSuccess: refresh });
  const milestoneDelete = useMutation({ mutationFn: (id: string) => deleteMilestone(projectId, id), onSuccess: refresh });
  const milestoneUpdate = useMutation({ mutationFn: (input: { id: string; status: "PENDING" | "IN_PROGRESS" | "COMPLETED" }) => updateMilestone(projectId, input.id, { status: input.status }), onSuccess: refresh });
  const memberAdd = useMutation({ mutationFn: (input: { userId: string; role: (typeof projectRoles)[number] }) => addProjectMember(projectId, input.userId, input.role), onSuccess: refresh });
  const memberRemove = useMutation({ mutationFn: (userId: string) => removeProjectMember(projectId, userId), onSuccess: refresh });
  const memberRole = useMutation({ mutationFn: (input: { userId: string; role: ProjectRole }) => updateProjectMemberRole(projectId, input.userId, input.role), onSuccess: refresh });
  if (query.isLoading) return <ScreenSkeleton title="Project" />;
  if (query.isError || !query.data) return <ScreenError title="Project could not be loaded" error={query.error} retry={() => query.refetch()} />;
  const { project, milestones, members, meetings, clients, users } = query.data;
  return <><PageHeader eyebrow={`${label(project.status)} · ${label(project.priority)} priority`} title={project.name} description={`${clientName(clients, project.clientId)}${project.description ? ` · ${project.description}` : ""}`} actions={<Button variant={project.archivedAt ? "secondary" : "danger"} loading={archive.isPending} onClick={() => archive.mutate(!project.archivedAt)}><Archive aria-hidden className="size-4" />{project.archivedAt ? "Restore" : "Archive"}</Button>} /><div className="mb-4 grid max-w-xl gap-2 sm:grid-cols-2"><Select aria-label="Project status" value={project.status} disabled={Boolean(project.archivedAt) || status.isPending} onValueChange={(value) => status.mutate(value as ProjectStatus)}>{projectStatuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select><Select aria-label="Project priority" value={project.priority} disabled={Boolean(project.archivedAt) || priorityUpdate.isPending} onValueChange={(value) => priorityUpdate.mutate(value as ProjectPriority)}>{projectPriorities.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></div>{status.error || priorityUpdate.error || archive.error ? <Alert variant="danger" title="Project could not be updated">{toAppError(status.error ?? priorityUpdate.error ?? archive.error).message}</Alert> : null}<Tabs defaultValue="milestones" items={[{ value: "milestones", label: `Milestones (${milestones.length})`, content: <MilestonesPanel projectArchived={Boolean(project.archivedAt)} milestones={milestones} createMutation={milestoneCreate} updateMutation={milestoneUpdate} completeMutation={milestoneComplete} deleteMutation={milestoneDelete} /> }, { value: "team", label: `Team (${members.length})`, content: <MembersPanel projectArchived={Boolean(project.archivedAt)} members={members} users={users} addMutation={memberAdd} roleMutation={memberRole} removeMutation={memberRemove} /> }, { value: "meetings", label: `Meetings (${meetings.length})`, content: meetings.length ? <MeetingRows meetings={meetings} clients={clients} /> : <CompactEmpty title="No project meetings" /> }, { value: "tasks", label: "Tasks", content: <EmptyState title="Tasks API not available" description="The current backend project module exposes projects, milestones, and members, but no task controller yet." /> }]} /></>;
}

export function MeetingsScreen() {
  const queryClient = useQueryClient();
  const [view, setView] = useState<MeetingView>("upcoming");
  const [adding, setAdding] = useState(false);
  const query = useQuery({ queryKey: workspaceKeys.meetings(view), queryFn: ({ signal }) => Promise.all([listMeetings(view, {}, signal), listClientOptions(signal), listProjects({ archived: false }, signal)]).then(([meetings, clients, projects]) => ({ meetings, clients, projects })) });
  const create = useMutation({ mutationFn: createMeeting, onSuccess: async () => { setAdding(false); await queryClient.invalidateQueries({ queryKey: workspaceKeys.all }); } });
  const cancel = useMutation({ mutationFn: cancelMeeting, onSuccess: () => queryClient.invalidateQueries({ queryKey: workspaceKeys.all }) });
  const reschedule = useMutation({ mutationFn: ({ id, startsAt }: { id: string; startsAt: string }) => updateMeeting(id, { startsAt }), onSuccess: () => queryClient.invalidateQueries({ queryKey: workspaceKeys.all }) });
  return <><PageHeader title="Meetings" description="Scheduled, past, and cancelled meetings from the live API." actions={<Button size="sm" onClick={() => setAdding((value) => !value)}><Plus aria-hidden className="size-4" />Schedule meeting</Button>} />{adding ? <MeetingCreateForm clients={query.data?.clients ?? []} projects={query.data?.projects ?? []} mutation={create} /> : null}<div className="mb-3 max-w-48"><Select aria-label="Meeting view" value={view} onValueChange={(value) => setView(value as MeetingView)}>{["all", "upcoming", "past", "cancelled"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></div>{query.isLoading ? <Skeleton className="h-72" /> : query.isError || !query.data ? <ScreenError title="Meetings could not be loaded" error={query.error} retry={() => query.refetch()} compact /> : query.data.meetings.length ? <Panel title=""><MeetingRows meetings={query.data.meetings} clients={query.data.clients} cancel={(id) => cancel.mutate(id)} reschedule={(id, startsAt) => reschedule.mutate({ id, startsAt })} {...(cancel.variables ? { cancellingId: cancel.variables } : {})} /></Panel> : <CompactEmpty title={`No ${view} meetings`} />}{cancel.error || reschedule.error ? <Alert variant="danger" title="Meeting could not be updated">{toAppError(cancel.error ?? reschedule.error).message}</Alert> : null}</>;
}

export function TeamScreen() {
  const queryClient = useQueryClient();
  const [inviting, setInviting] = useState(false);
  const query = useQuery({ queryKey: workspaceKeys.users(), queryFn: ({ signal }) => listUsers(1, 100, signal) });
  const invite = useMutation({ mutationFn: inviteUser, onSuccess: async () => { setInviting(false); await Promise.all([queryClient.invalidateQueries({ queryKey: workspaceKeys.users() }), queryClient.invalidateQueries({ queryKey: [...workspaceKeys.all, "invitations"] })]); } });
  const active = useMutation({ mutationFn: ({ id, value }: { id: string; value: boolean }) => setUserActive(id, value), onSuccess: () => queryClient.invalidateQueries({ queryKey: workspaceKeys.users() }) });
  const roleUpdate = useMutation({ mutationFn: ({ id, role }: { id: string; role: "ADMIN" | "MEMBER" }) => updateUser(id, { role }), onSuccess: () => queryClient.invalidateQueries({ queryKey: workspaceKeys.users() }) });
  return <><PageHeader title="Team" description="Manage organization members, pending invitations, and access roles." actions={<Button size="sm" onClick={() => setInviting((value) => !value)}><Plus aria-hidden className="size-4" />Invite member</Button>} />{inviting ? <InviteForm mutation={invite} /> : null}{query.isLoading ? <Skeleton className="h-72" /> : query.isError || !query.data ? <ScreenError title="Team could not be loaded" error={query.error} retry={() => query.refetch()} compact /> : query.data.data.length ? <Panel title=""><Table><TableHead><tr><TableHeader>Member</TableHeader><TableHeader>Role</TableHeader><TableHeader>Last login</TableHeader><TableHeader>Status</TableHeader><TableHeader>Action</TableHeader></tr></TableHead><TableBody>{query.data.data.map((user) => <TableRow key={user.id}><TableCell><p className="font-medium">{user.name}</p><p className="text-xs text-text-muted">{user.email}</p></TableCell><TableCell><Select aria-label={`Role for ${user.name}`} value={user.role} disabled={roleUpdate.isPending} onValueChange={(role) => roleUpdate.mutate({ id: user.id, role: role as "ADMIN" | "MEMBER" })}><option value="MEMBER">Member</option><option value="ADMIN">Admin</option></Select></TableCell><TableCell>{user.lastLoginAt ? format(new Date(user.lastLoginAt), "d MMM yyyy, HH:mm") : "Never"}</TableCell><TableCell><div className="flex flex-wrap gap-1"><Badge tone={user.isActive ? "success" : "warning"}>{user.isActive ? "Active" : "Inactive"}</Badge>{user.emailVerifiedAt ? null : <Badge tone="warning">Unverified</Badge>}</div></TableCell><TableCell><Button size="sm" variant="secondary" loading={active.isPending && active.variables?.id === user.id} onClick={() => active.mutate({ id: user.id, value: !user.isActive })}>{user.isActive ? "Deactivate" : "Activate"}</Button></TableCell></TableRow>)}</TableBody></Table></Panel> : <CompactEmpty title="No team members" />}{active.error || roleUpdate.error ? <Alert variant="danger" title="Team member could not be updated">{toAppError(active.error ?? roleUpdate.error).message}</Alert> : null}<InvitationsPanel /></>;
}

// Invitations are admin-only upstream; a 403 here just means the signed-in user is a member.
function InvitationsPanel() {
  const queryClient = useQueryClient();
  const [status, setStatus] = useState<InvitationStatus>("PENDING");
  const query = useQuery({ queryKey: workspaceKeys.invitations(status), queryFn: ({ signal }) => listInvitations(status, 1, 100, signal), retry: false });
  const invalidate = () => queryClient.invalidateQueries({ queryKey: [...workspaceKeys.all, "invitations"] });
  const resend = useMutation({ mutationFn: resendInvitation, onSuccess: invalidate });
  const revoke = useMutation({ mutationFn: revokeInvitation, onSuccess: invalidate });
  if (toAppError(query.error).status === 403) return null;

  const filter = <Select aria-label="Invitation status" value={status} onValueChange={(value) => setStatus(value as InvitationStatus)}>{invitationStatuses.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select>;
  return <section className="mt-8 grid gap-4"><SectionHeader title="Invitations" description="Invited people appear here until they accept the emailed link." action={filter} />{query.isLoading ? <Skeleton className="h-40" /> : query.isError || !query.data ? <ScreenError title="Invitations could not be loaded" error={query.error} retry={() => query.refetch()} compact /> : query.data.data.length ? <Panel title=""><Table><TableHead><tr><TableHeader>Invitee</TableHeader><TableHeader>Role</TableHeader><TableHeader>Status</TableHeader><TableHeader>Email</TableHeader><TableHeader>Expires</TableHeader><TableHeader>Action</TableHeader></tr></TableHead><TableBody>{query.data.data.map((invitation) => <TableRow key={invitation.id}><TableCell><p className="font-medium">{invitation.name}</p><p className="text-xs text-text-muted">{invitation.email}</p></TableCell><TableCell>{label(invitation.role)}</TableCell><TableCell><Badge tone={invitationTone(invitation.status)}>{label(invitation.status)}</Badge></TableCell><TableCell><Badge tone={deliveryTone(invitation.emailStatus)}>{label(invitation.emailStatus)}</Badge>{invitation.emailAttemptCount > 1 ? <span className="ml-2 text-xs text-text-muted">{invitation.emailAttemptCount} attempts</span> : null}</TableCell><TableCell>{format(new Date(invitation.expiresAt), "d MMM yyyy, HH:mm")}</TableCell><TableCell>{invitation.status === "ACCEPTED" || invitation.status === "REVOKED" ? <span className="text-xs text-text-muted">No action</span> : <div className="flex gap-2"><Button size="sm" variant="secondary" loading={resend.isPending && resend.variables === invitation.id} onClick={() => resend.mutate(invitation.id)}><RotateCw aria-hidden className="size-4" />Resend</Button><Button size="sm" variant="ghost" loading={revoke.isPending && revoke.variables === invitation.id} onClick={() => revoke.mutate(invitation.id)}>Revoke</Button></div>}</TableCell></TableRow>)}</TableBody></Table></Panel> : <CompactEmpty title={`No ${status.toLowerCase()} invitations`} />}{resend.error || revoke.error ? <Alert variant="danger" title="Invitation could not be updated">{toAppError(resend.error ?? revoke.error).message}</Alert> : null}</section>;
}

function deliveryTone(status: EmailDeliveryStatus) {
  if (status === "FAILED" || status === "BOUNCED" || status === "SUPPRESSED" || status === "COMPLAINED") return "danger" as const;
  if (status === "DELIVERED" || status === "SUBMITTED") return "success" as const;
  if (status === "DELAYED") return "warning" as const;
  return "neutral" as const;
}

function invitationTone(status: InvitationStatus) {
  if (status === "ACCEPTED") return "success" as const;
  if (status === "PENDING") return "info" as const;
  return "warning" as const;
}

export function DocumentsScreen() { return <><PageHeader title="Document Center" description="Document storage is planned but is not present in the current backend build." /><EmptyState title="Documents API not available" description="This screen will connect when the backend adds its document controller and response contract." /></>; }
export function ActivityScreen() { return <><PageHeader title="Activity Feed" description="The backend records activity internally but does not yet expose a company-wide read endpoint." /><EmptyState title="Activity feed API not available" description="Per-client activity is live on each client page. A unified feed will appear here when /activities is implemented." /></>; }

function ProjectCreateForm({ clients, mutation }: { clients: ClientOption[]; mutation: MutationLike<ProjectInput> }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate({ name: String(data.get("name") ?? ""), clientId: String(data.get("clientId") ?? ""), ...optionalFields(data, ["description", "startDate", "dueDate"]), priority: String(data.get("priority") ?? "MEDIUM") as ProjectPriority }); };
  return <ActionForm title="Create project" onSubmit={submit} error={mutation.error} pending={mutation.isPending}><FormField label="Project name" required><Input name="name" required minLength={2} /></FormField><FormField label="Client" required><Select name="clientId" required defaultValue=""><option value="">Select a client</option>{clients.filter((client) => client.status === "ACTIVE").map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></FormField><FormField label="Priority"><Select name="priority" defaultValue="MEDIUM">{projectPriorities.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select></FormField><FormField label="Start date"><Input type="date" name="startDate" /></FormField><FormField label="Due date"><Input type="date" name="dueDate" /></FormField><FormField label="Description"><Textarea name="description" /></FormField></ActionForm>;
}

function MeetingCreateForm({ clients, projects, mutation }: { clients: ClientOption[]; projects: Awaited<ReturnType<typeof listProjects>>; mutation: MutationLike<MeetingInput> }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const local = String(data.get("startsAt") ?? ""); mutation.mutate({ title: String(data.get("title") ?? ""), startsAt: new Date(local).toISOString(), ...optionalFields(data, ["agenda", "meetingUrl", "clientId", "projectId"]) }); };
  return <ActionForm title="Schedule meeting" onSubmit={submit} error={mutation.error} pending={mutation.isPending}><FormField label="Title" required><Input name="title" required minLength={2} /></FormField><FormField label="Start" required><Input type="datetime-local" name="startsAt" required /></FormField><FormField label="Client"><Select name="clientId" defaultValue=""><option value="">Internal meeting</option>{clients.filter((client) => client.status === "ACTIVE").map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></FormField><FormField label="Project"><Select name="projectId" defaultValue=""><option value="">No project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select></FormField><FormField label="Meeting URL"><Input type="url" name="meetingUrl" placeholder="https://meet.example.com/..." /></FormField><FormField label="Agenda"><Textarea name="agenda" /></FormField></ActionForm>;
}

function InviteForm({ mutation }: { mutation: MutationLike<{ name: string; email: string; role: "ADMIN" | "MEMBER" }> }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate({ name: String(data.get("name") ?? ""), email: String(data.get("email") ?? ""), role: String(data.get("role") ?? "MEMBER") as "ADMIN" | "MEMBER" }); }; return <ActionForm title="Invite team member" onSubmit={submit} error={mutation.error} pending={mutation.isPending}><FormField label="Name" required><Input name="name" required minLength={2} /></FormField><FormField label="Email" required><Input name="email" type="email" required /></FormField><FormField label="Role"><Select name="role" defaultValue="MEMBER"><option value="MEMBER">Member</option><option value="ADMIN">Admin</option></Select></FormField></ActionForm>; }

function MilestonesPanel({ projectArchived, milestones, createMutation, updateMutation, completeMutation, deleteMutation }: { projectArchived: boolean; milestones: Awaited<ReturnType<typeof listMilestones>>; createMutation: MutationLike<{ title: string; description?: string; dueDate?: string }>; updateMutation: MutationLike<{ id: string; status: "PENDING" | "IN_PROGRESS" | "COMPLETED" }>; completeMutation: MutationLike<string>; deleteMutation: MutationLike<string> }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createMutation.mutate({ title: String(data.get("title") ?? ""), ...optionalFields(data, ["description", "dueDate"]) }); };
  return <div className="grid gap-4"><form onSubmit={submit} className="flex flex-wrap gap-2"><Input name="title" required minLength={2} placeholder="New milestone" className="min-w-56 flex-1" /><Input name="dueDate" type="date" aria-label="Milestone due date" className="w-auto" /><Button type="submit" disabled={projectArchived} loading={createMutation.isPending}><Plus aria-hidden className="size-4" />Add</Button></form>{milestones.length ? <div className="divide-y rounded-[var(--radius-md)] border">{milestones.map((milestone) => <div key={milestone.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{milestone.title}</p><p className="text-xs text-text-muted">{milestone.dueDate ? `Due ${format(new Date(milestone.dueDate), "d MMM yyyy")}` : "No due date"}</p></div><div className="flex items-center gap-2"><Select aria-label={`Status for ${milestone.title}`} value={milestone.status} disabled={projectArchived || updateMutation.isPending} onValueChange={(value) => updateMutation.mutate({ id: milestone.id, status: value as "PENDING" | "IN_PROGRESS" | "COMPLETED" })}><option value="PENDING">Pending</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></Select>{milestone.status !== "COMPLETED" ? <Button size="sm" variant="secondary" onClick={() => completeMutation.mutate(milestone.id)}><Check aria-hidden className="size-4" />Complete</Button> : null}<Button size="sm" variant="ghost" onClick={() => deleteMutation.mutate(milestone.id)}><Trash2 aria-hidden className="size-4" />Delete</Button></div></div>)}</div> : <CompactEmpty title="No milestones" />}</div>;
}

function MembersPanel({ projectArchived, members, users, addMutation, roleMutation, removeMutation }: { projectArchived: boolean; members: Awaited<ReturnType<typeof listProjectMembers>>; users: Awaited<ReturnType<typeof listUsers>>["data"]; addMutation: MutationLike<{ userId: string; role: ProjectRole }>; roleMutation: MutationLike<{ userId: string; role: ProjectRole }>; removeMutation: MutationLike<string> }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addMutation.mutate({ userId: String(data.get("userId") ?? ""), role: String(data.get("role") ?? "MEMBER") as ProjectRole }); };
  const existing = new Set(members.map((member) => member.userId));
  return <div className="grid gap-4"><form onSubmit={submit} className="flex flex-wrap gap-2"><Select name="userId" required defaultValue="" className="min-w-56"><option value="">Select team member</option>{users.filter((user) => user.isActive && !existing.has(user.id)).map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</Select><Select name="role" defaultValue="MEMBER">{projectRoles.map((role) => <option key={role} value={role}>{label(role)}</option>)}</Select><Button type="submit" disabled={projectArchived} loading={addMutation.isPending}><UsersRound aria-hidden className="size-4" />Add member</Button></form>{members.length ? <div className="divide-y rounded-[var(--radius-md)] border">{members.map((member) => <div key={member.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium">{member.user.name}</p><p className="text-xs text-text-muted">{member.user.email}</p></div><div className="flex items-center gap-2"><Select aria-label={`Project role for ${member.user.name}`} value={member.role} disabled={projectArchived || roleMutation.isPending} onValueChange={(role) => roleMutation.mutate({ userId: member.userId, role: role as ProjectRole })}>{projectRoles.map((role) => <option key={role} value={role}>{label(role)}</option>)}</Select><Button size="sm" variant="ghost" disabled={member.role === "OWNER"} onClick={() => removeMutation.mutate(member.userId)}><Trash2 aria-hidden className="size-4" />Remove</Button></div></div>)}</div> : <CompactEmpty title="No project members" />}</div>;
}

function MeetingRows({ meetings, clients, cancel, cancellingId, reschedule }: { meetings: Awaited<ReturnType<typeof listMeetings>>; clients: ClientOption[]; cancel?: (id: string) => void; cancellingId?: string; reschedule?: (id: string, startsAt: string) => void }) {
  return <div className="divide-y">{meetings.map((meeting) => <article key={meeting.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto]"><div><p className="font-medium">{meeting.title}</p><p className="mt-1 text-xs text-text-muted">{format(new Date(meeting.startsAt), "d MMM yyyy, HH:mm")} · {meeting.clientId ? clientName(clients, meeting.clientId) : "Internal"}</p>{meeting.agenda ? <p className="mt-2 text-sm text-text-secondary">{meeting.agenda}</p> : null}{reschedule && !meeting.cancelledAt && new Date(meeting.startsAt) > new Date() ? <form className="mt-3 flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); reschedule(meeting.id, new Date(String(data.get("startsAt"))).toISOString()); }}><Input type="datetime-local" name="startsAt" aria-label={`Start time for ${meeting.title}`} defaultValue={format(new Date(meeting.startsAt), "yyyy-MM-dd'T'HH:mm")} className="w-auto" /><Button type="submit" size="sm" variant="secondary">Save time</Button></form> : null}</div><div className="flex items-center gap-2"><Badge tone={meeting.cancelledAt ? "danger" : "info"}>{meeting.cancelledAt ? "Cancelled" : "Scheduled"}</Badge>{meeting.meetingUrl && !meeting.cancelledAt ? <a href={meeting.meetingUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-8 items-center gap-1 rounded-md border px-3 text-xs"><ExternalLink aria-hidden className="size-3" />Join</a> : null}{cancel && !meeting.cancelledAt && new Date(meeting.startsAt) > new Date() ? <Button size="sm" variant="secondary" loading={cancellingId === meeting.id} onClick={() => cancel(meeting.id)}>Cancel</Button> : null}</div></article>)}</div>;
}

function ActionForm({ title, onSubmit, error, pending, children }: { title: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; error: unknown; pending: boolean; children: ReactNode }) { return <Panel title={title} className="mb-4"><form onSubmit={onSubmit} className="grid gap-3 sm:grid-cols-2">{children}<div className="sm:col-span-2"><Button type="submit" loading={pending}>Save</Button></div>{error ? <div className="sm:col-span-2"><Alert variant="danger" title="Could not save">{toAppError(error).message}</Alert></div> : null}</form></Panel>; }
function Panel({ title, className = "", children }: { title: string; className?: string; children: ReactNode }) { return <section className={`surface-panel p-4 ${className}`}>{title ? <SectionHeader title={title} /> : null}{children}</section>; }
function CompactEmpty({ title }: { title: string }) { return <EmptyState title={title} description="No matching records were returned by the backend." />; }
function ScreenSkeleton({ title }: { title: string }) { return <><PageHeader title={title} /><Skeleton className="h-72" /></>; }
function ScreenError({ title, error, retry, compact = false }: { title: string; error: unknown; retry: () => unknown; compact?: boolean }) { const content = <Alert variant="danger" title={title} action={<Button size="sm" variant="secondary" onClick={() => void retry()}><RotateCw aria-hidden className="size-4" />Retry</Button>}>{toAppError(error).message}</Alert>; return compact ? content : <><PageHeader title={title} />{content}</>; }
function clientName(clients: ClientOption[], id: string) { return clients.find((client) => client.id === id)?.name ?? "Unknown client"; }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
function projectTone(status: ProjectStatus): "success" | "warning" | "info" { return status === "COMPLETED" ? "success" : status === "ON_HOLD" ? "warning" : "info"; }
function optionalFields(data: FormData, keys: string[]) { return Object.fromEntries(keys.flatMap((key) => { const value = String(data.get(key) ?? "").trim(); return value ? [[key, key.toLowerCase().includes("date") ? new Date(value).toISOString() : value]] : []; })); }
